In [2]:
import numpy as np
import re
import random
import time
import os
import sys

from common_utils import strToSuffix



In [9]:
import argparse
parser = argparse.ArgumentParser(description='Arguments for DANIEL_FJSP')

# args for env
parser.add_argument('--n_j', type=int, default=10, help='Number of jobs of the instance')
parser.add_argument('--n_m', type=int, default=5, help='Number of machines of the instance')
parser.add_argument('--n_op', type=int, default=60, help='Number of operations of the instance')
parser.add_argument('--low', type=int, default=1, help='Lower Bound of processing time(PT)')
parser.add_argument('--high', type=int, default=99, help='Upper Bound of processing time')
parser.add_argument('--data_suffix', type=str, default='mix', help='Suffix of the data')
parser.add_argument('--op_per_mch_min', type=int, default=1,
                    help='Minimum number of compatible machines for each operation')
parser.add_argument('--op_per_mch_max', type=int, default=5,
                    help='Maximum number of compatible machines for each operation')
parser.add_argument('--op_per_job', type=float, default=0,
                    help='Number of operations per job, default 0, means the number equals m')

config = parser.parse_args(args=[])



In [10]:


n_j=None
n_m=None

if n_j is None:n_j = config.n_j 
if n_m is None:n_m = config.n_m 
if config.op_per_job == 0:
    op_per_job = n_m
else:
    op_per_job = config.op_per_job

low = config.low
high = config.high
data_suffix = config.data_suffix

op_per_mch_min = 1
if data_suffix == "nf":
    op_per_mch_max = 1
elif data_suffix == "mix":
    op_per_mch_max = n_m
else:
    op_per_mch_min = config.op_per_mch_min
    op_per_mch_max = config.op_per_mch_max
if op_per_mch_min < 1 or op_per_mch_max > n_m:
    print(f'Error from Instance Generation: [{op_per_mch_min},{op_per_mch_max}] '
            f'with num_mch : {n_m}')
    sys.exit()

n_op = int(n_j * op_per_job)
job_length = np.full(shape=(n_j,), fill_value=op_per_job, dtype=int)
op_use_mch = np.random.randint(low=op_per_mch_min, high=op_per_mch_max + 1,
                                size=n_op)

op_per_mch = np.mean(op_use_mch)
op_pt = np.random.randint(low=low, high=high + 1, size=(n_op, n_m))

for row in range(op_pt.shape[0]):
    mch_num = int(op_use_mch[row])
    if mch_num < n_m:
        inf_pos = np.random.choice(np.arange(0, n_m), n_m - mch_num, replace=False)
        op_pt[row][inf_pos] = 0

job_length, op_pt, op_per_mch


(array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]),
 array([[56,  0,  0,  0,  0],
        [56, 22, 68, 24, 51],
        [96,  0, 12,  0, 95],
        [68, 47,  5, 89, 77],
        [74,  0, 99, 46,  0],
        [ 0,  0,  0, 61,  0],
        [33, 79, 62,  0,  0],
        [21, 39, 61,  4,  0],
        [ 0,  0,  0, 97,  0],
        [ 0,  0, 20,  0, 67],
        [40, 94, 36, 79, 90],
        [36, 35, 33, 16, 23],
        [ 0,  0,  0, 74,  0],
        [75, 57, 19,  7, 21],
        [88, 90,  0, 83, 68],
        [ 0,  0, 38, 48,  0],
        [76, 60,  0, 95,  0],
        [11, 38,  2,  0, 29],
        [18, 78, 13,  0, 82],
        [62,  0,  0,  0,  0],
        [76, 34, 55, 41, 25],
        [ 0, 54,  0,  0, 34],
        [ 0, 48,  0,  0,  0],
        [90,  0, 34, 49,  0],
        [36,  9,  0,  0,  0],
        [14, 26,  0, 54,  7],
        [ 0,  0, 73,  0, 34],
        [79, 12, 21, 61,  0],
        [ 4, 16, 11,  0, 35],
        [98,  2,  1,  0,  0],
        [89,  0,  0,  0,  0],
        [76, 18, 33, 88, 46],


In [12]:
import numpy as np

def generate_flexible_job_shop(num_jobs, num_machines):
    job_length = np.random.randint(2, 6, size=num_jobs)
    total_operations = sum(job_length)
    op_pt = np.zeros((total_operations, num_machines))
    total_machines_per_op = 0

    op_index = 0
    for job in range(num_jobs):
        for _ in range(job_length[job]):
            num_machines_for_op = np.random.randint(1, num_machines + 1)
            total_machines_per_op += num_machines_for_op
            machines_for_op = np.random.choice(num_machines, num_machines_for_op, replace=False)
            
            for machine in machines_for_op:
                op_pt[op_index, machine] = np.random.randint(1, 99)  # Random processing time

            op_index += 1

    op_per_mch = total_machines_per_op / total_operations
    return job_length, op_pt, op_per_mch

# Example call
num_jobs = 10
num_machines = 5
job_length, op_pt, op_per_mch = generate_flexible_job_shop(num_jobs, num_machines)
job_length, op_pt, op_per_mch

(array([2, 2, 3, 5, 3, 5, 3, 5, 2, 5]),
 array([[49., 87., 28., 96.,  0.],
        [21., 11., 47.,  0., 54.],
        [61.,  0., 38.,  0.,  0.],
        [61.,  0.,  0.,  0., 15.],
        [ 0.,  0., 27., 22.,  0.],
        [87.,  0.,  0., 94.,  0.],
        [ 0., 55., 33., 60., 64.],
        [89., 50.,  0.,  0.,  0.],
        [ 0., 20.,  0., 21.,  0.],
        [ 0., 74., 56.,  0., 89.],
        [ 0., 56.,  0.,  0., 93.],
        [ 0., 47., 95.,  0.,  0.],
        [79.,  0.,  4.,  2., 58.],
        [68., 47., 88., 32.,  0.],
        [ 0., 69.,  0.,  6.,  0.],
        [49.,  0., 66.,  0.,  0.],
        [67., 92., 95.,  0., 79.],
        [87., 97., 17., 23., 18.],
        [ 0., 49., 75.,  0., 49.],
        [ 2.,  0., 64.,  0., 75.],
        [ 0.,  0.,  0., 64.,  0.],
        [92., 91.,  0., 52., 13.],
        [72., 82., 95., 63., 27.],
        [80.,  0., 53.,  0.,  0.],
        [93., 27., 77., 98., 55.],
        [ 0.,  0.,  0.,  0., 86.],
        [30., 47., 69., 56., 87.],
        [ 0., 3

In [ ]:
job_init = config.n_j

num_jobs = job_init
if not self.flag_same_opes:
    self.nums_ope = [random.randint(self.opes_per_job_min, self.opes_per_job_max) for _ in range(self.num_jobs)]
self.num_opes = sum(self.nums_ope)
self.nums_option = [random.randint(self.mas_per_ope_min, self.mas_per_ope_max) for _ in range(self.num_opes)]
self.num_options = sum(self.nums_option)

self.ope_ma = []
for val in self.nums_option:
    self.ope_ma = self.ope_ma + sorted(random.sample(range(1, self.num_mas + 1), val))
self.proc_time = []

self.proc_times_mean = [random.randint(self.proctime_per_ope_min, self.proctime_per_ope_max) for _ in
                        range(self.num_opes)]
for i in range(len(self.nums_option)):
    low_bound = max(self.proctime_per_ope_min, round(self.proc_times_mean[i] * (1 - self.proctime_dev)))
    high_bound = min(self.proctime_per_ope_max, round(self.proc_times_mean[i] * (1 + self.proctime_dev)))
    proc_time_ope = [random.randint(low_bound, high_bound) for _ in range(self.nums_option[i])]
    self.proc_time = self.proc_time + proc_time_ope

self.num_ope_biass = [sum(self.nums_ope[0:i]) for i in range(self.num_jobs)]
self.num_ma_biass = [sum(self.nums_option[0:i]) for i in range(self.num_opes)]
line0 = '{0}\t{1}\t{2}\n'.format(self.num_jobs, self.num_mas, self.num_options / self.num_opes)
lines_doc = []
lines_doc.append('{0}\t{1}\t{2}'.format(self.num_jobs, self.num_mas, self.num_options / self.num_opes))
for i in range(self.num_jobs):
    flag = 0
    flag_time = 0
    flag_new_ope = 1
    idx_ope = -1
    idx_ma = 0
    line = []
    option_max = sum(self.nums_option[self.num_ope_biass[i]:(self.num_ope_biass[i] + self.nums_ope[i])])
    idx_option = 0
    while True:
        if flag == 0:
            line.append(self.nums_ope[i])
            flag += 1
        elif flag == flag_new_ope:
            idx_ope += 1
            idx_ma = 0
            flag_new_ope += self.nums_option[self.num_ope_biass[i] + idx_ope] * 2 + 1
            line.append(self.nums_option[self.num_ope_biass[i] + idx_ope])
            flag += 1
        elif flag_time == 0:
            line.append(self.ope_ma[self.num_ma_biass[self.num_ope_biass[i] + idx_ope] + idx_ma])
            flag += 1
            flag_time = 1
        else:
            line.append(self.proc_time[self.num_ma_biass[self.num_ope_biass[i] + idx_ope] + idx_ma])
            flag += 1
            flag_time = 0
            idx_option += 1
            idx_ma += 1
        if idx_option == option_max:
            str_line = " ".join([str(val) for val in line])
            lines_doc.append(str_line)
            break
job_length, op_pt = text_to_matrix(lines_doc)

job_length, op_pt
