In [1]:
import os, sys
os.environ['ON_PY']="1"
from params import parser
from common_utils import setup_seed
from data_utils import pack_data_from_config
import numpy as np
from test_script.base import Test
import matplotlib.pyplot as plt
import numpy as np

notebook_dir = os.getcwd()
print(notebook_dir)
# 将工作目录更改为上一级目录
os.chdir("/home/wlc/FJSP-DRL-MAML")


(CVXPY) Mar 27 08:39:53 PM: Encountered unexpected exception importing solver GLOP:
RuntimeError('Unrecognized new version of ortools (9.8.3296). Expected < 9.5.0.Please open a feature request on cvxpy to enable support for this version.')
(CVXPY) Mar 27 08:39:53 PM: Encountered unexpected exception importing solver PDLP:
RuntimeError('Unrecognized new version of ortools (9.8.3296). Expected < 9.5.0.Please open a feature request on cvxpy to enable support for this version.')


/home/wlc/miniconda3/envs/RL-torch/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/wlc/miniconda3/envs/RL-torch/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda9SetDeviceEi'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(


/home/wlc/FJSP-DRL-MAML/experiment


In [2]:
pack_data_from_config("SD2EC", ["10x5+mix", "20x5+mix", "15x10+mix", "20x10+mix"])

[(([array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32),
    array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32),
    array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32),
    array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32),
    array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32),
    array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32),
    array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32),
    array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32),
    array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32),
    array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32)],
   [array([[84, 79, 89, 45, 94],
           [93,  0,  0,  0, 88],
           [85, 85,  0, 35, 85],
           [ 0, 97, 98,  0, 95],
           [91, 79, 96,  0, 82],
           [87,  0,  0,  0,  0],
           [83,  0, 96, 41, 86],
           [98, 95, 91, 47, 83],
           [81, 91, 82, 45, 92],
           [83, 91, 82, 48, 94],
           [ 0, 91,  0,  0,  0],
           [81, 94,  0,  0,  0],
           [90, 86, 97, 32, 93],
          