In [5]:
import torch

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [6]:
Q = 3*a**3 - b**2

In [7]:
torch.autograd.grad(Q, a)

RuntimeError: grad can be implicitly created only for scalar outputs

In [3]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)
external_grad

tensor([1., 1.])

In [8]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [9]:
print(x.data)

tensor([[1., 1.],
        [1., 1.]])


In [10]:
print(x.grad)

None


In [14]:
print(x.grad_fn)  # we've created x ourselves

None


In [12]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [13]:
print(y.grad_fn)

In [5]:
import numpy as np

# 假设选择的索引
self_env_idxs = np.array([0, 1])
chosen_job = np.array([3, 5])
chosen_mch = np.array([1, 2])

# 输入张量
arr2 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15],
                  [16, 17, 18], [19, 20, 21], [22, 23, 24], [25, 26, 27], [28, 29, 30],
                  [31, 32, 33], [34, 35, 36], [37, 38, 39], [40, 41, 42], [43, 44, 45]],
                 [[46, 47, 48], [49, 50, 51], [52, 53, 54], [55, 56, 57], [58, 59, 60],
                  [61, 62, 63], [64, 65, 66], [67, 68, 69], [70, 71, 72], [73, 74, 75],
                  [76, 77, 78], [79, 80, 81], [82, 83, 84], [85, 86, 87], [88, 89, 90]]])

# 复制原始张量
zero_tensor = np.copy(arr2)

# 将指定位置修改为0，并填充相应的元素
zero_tensor[self_env_idxs[:, np.newaxis], chosen_job[:, np.newaxis], :] = 0
zero_tensor[self_env_idxs[:, np.newaxis], chosen_job[:, np.newaxis], chosen_mch[:, np.newaxis]] = \
    arr2[self_env_idxs[:, np.newaxis], chosen_job[:, np.newaxis], chosen_mch[:, np.newaxis]]

print("生成的张量：")
print(zero_tensor)


生成的张量：
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0 11  0]
  [13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]
  [25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]
  [37 38 39]
  [40 41 42]
  [43 44 45]]

 [[46 47 48]
  [49 50 51]
  [52 53 54]
  [55 56 57]
  [58 59 60]
  [ 0  0 63]
  [64 65 66]
  [67 68 69]
  [70 71 72]
  [73 74 75]
  [76 77 78]
  [79 80 81]
  [82 83 84]
  [85 86 87]
  [88 89 90]]]


In [6]:
import numpy as np

# 给定的平均操作时间
mch_mean_pt = np.array([[0.62626263, 0.67125803, 0.47785548],
                        [0.42501942, 0.41792929, 0.61111111]])

# 随机生成每个环境中每台机器的平均能耗（范围在0.5到1之间）
mch_mean_energy = np.random.uniform(0.5, 1, size=mch_mean_pt.shape)

# 计算每台机器的功耗
mch_power_consumption = mch_mean_pt * mch_mean_energy

# 计算每个环境的总功耗
env_power_consumption = np.sum(mch_power_consumption, axis=1, keepdims=True)

print("每个环境的机器功耗：")
print(env_power_consumption)


每个环境的机器功耗：
[[1.5015982 ]
 [1.22925678]]


In [8]:
import numpy as np

# 给定的最大完工时间
max_endTime = np.array([1.41414141, 1.02020202])

# 给定的平均操作时间
mch_mean_pt = np.array([[0.62626263, 0.67125803, 0.47785548],
                        [0.42501942, 0.41792929, 0.61111111]])

# 随机生成每个环境中每台机器的待机功率（范围在0.1到0.2之间）
mch_idle_power = np.random.uniform(0.1, 0.2, size=mch_mean_pt.shape)

# 计算每个环境中所有机器的总待机时间
env_idle_time = np.sum(mch_idle_power * max_endTime[:, np.newaxis], axis=1)

print("每个环境的总待机时间：")
print(env_idle_time, mch_idle_power)


每个环境的总待机时间：
[0.73806071 0.52311109] [[0.19623284 0.19703245 0.12864908]
 [0.1549593  0.18843454 0.16935862]]


In [14]:
def calculate_dividends(total_value, product_prices):
    # 计算第一个产品的总价值（打五折）
    if len(product_prices) < 2: return ""
    product_prices[0] = product_prices[0] * 0.5
    product_prices[1] = 0
    # 计算后面产品的总价值
    remaining_value = sum(product_prices)
    product_prices[1] = total_value - remaining_value
    # 如果后面的产品总价值小于等于第一个产品的总价值
    
    dividend_ratios = ["{:.2f}".format(price / total_value) for price in product_prices]
    return " ".join(dividend_ratios)
# 示例用法
total_value = 30
product_prices = [10, 30, 12.5]
dividends = calculate_dividends(total_value, product_prices)
print(dividends)


0.17 0.42 0.42
