In [6]:
import numpy as np

# 创建一个(2,6,3)的随机数组
arr = np.random.randint(0, 100, size=(2, 6, 3))
print(arr)

# 找出最大值的索引
max_index = np.argmax(arr, axis=-1)

print(max_index)
arr[:,:, max_index]


[[[12 68 23]
  [27  6 63]
  [ 0 65 76]
  [66 18 46]
  [42 52 99]
  [ 2 19 91]]

 [[88 11 75]
  [98 25 19]
  [46 66 47]
  [69 76 15]
  [ 4 74 74]
  [33 14 49]]]
[[1 2 2 0 2 2]
 [0 0 1 1 1 2]]


array([[[[68, 23, 23, 12, 23, 23],
         [12, 12, 68, 68, 68, 23]],

        [[ 6, 63, 63, 27, 63, 63],
         [27, 27,  6,  6,  6, 63]],

        [[65, 76, 76,  0, 76, 76],
         [ 0,  0, 65, 65, 65, 76]],

        [[18, 46, 46, 66, 46, 46],
         [66, 66, 18, 18, 18, 46]],

        [[52, 99, 99, 42, 99, 99],
         [42, 42, 52, 52, 52, 99]],

        [[19, 91, 91,  2, 91, 91],
         [ 2,  2, 19, 19, 19, 91]]],


       [[[11, 75, 75, 88, 75, 75],
         [88, 88, 11, 11, 11, 75]],

        [[25, 19, 19, 98, 19, 19],
         [98, 98, 25, 25, 25, 19]],

        [[66, 47, 47, 46, 47, 47],
         [46, 46, 66, 66, 66, 47]],

        [[76, 15, 15, 69, 15, 15],
         [69, 69, 76, 76, 76, 15]],

        [[74, 74, 74,  4, 74, 74],
         [ 4,  4, 74, 74, 74, 74]],

        [[14, 49, 49, 33, 49, 49],
         [33, 33, 14, 14, 14, 49]]]])

In [10]:
import numpy as np

# 初始化机器数组
machines = np.zeros((2, 3))

# 假设这是你的 unscheduled_energy_lb_idx 数组
unscheduled_energy_lb_idx = np.array([[0, 1, 2, 0, 1, 2],
                                      [1, 2, 0, 1, 2, 0]])

# 假设这是你的 unscheduled_energy_lb_energy 数组
unscheduled_energy_lb_energy = np.array([[10, 20, 30, 40, 50, 60],
                                         [15, 25, 35, 45, 55, 65]])

# 遍历并将能量最小值加到对应的机器上
for i in range(unscheduled_energy_lb_idx.shape[0]):  # 遍历每行
    for j in range(unscheduled_energy_lb_idx.shape[1]):  # 遍历每列
        idx = unscheduled_energy_lb_idx[i, j]  # 获取当前能量值对应的机器索引
        energy = unscheduled_energy_lb_energy[i, j]  # 获取当前的能量值
        machines[i, idx] += energy  # 将能量值加到对应的机器上

print(machines)


[[ 50.  70.  90.]
 [100.  60.  80.]]
